services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    env_file: ".env"
    networks:
      - inception
    volumes:
      -  /home/eburnet/data/mariadb:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 20s
      interval: 5s
      timeout: 10s
      retries: 5

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    build: ./requirements/wordpress
    env_file: ".env"
    networks:
      - inception
    volumes:
      - /home/eburnet/data/wp:/var/www/html
    restart: on-failure
    
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    env_file: ".env"
    networks:
      - inception
    volumes:
      - /home/eburnet/data/wp:/var/www/html
    restart: on-failure

networks:
  inception: